print ("1234567890123456789012345678901234567890")
print (1, 2, 3)
print ("Computers are fun")
print ("Computers", "are", "fun")
print ("Computers" + "are" + "fun")
# See if this statement appears on the screen
print ("Computer", "Programming", "Class")
print ("Computer" + "Programming" + "Class")
print ("Look")
print ("How")
print ("This Works")
print ("Look", end = "")
print ("How" , end = "")
print ("This Works")
print ("Look how numbers print")
print (4)
print ("4")
print (64/4)
print ("64/4")
print (8*3)
print ("8*3")
print ("6+2=", end = "")
print (6+2)
print (19//4)
print (19.0/4)
print (19%4)
print ("This produces two blank lines")
print ()
print ()
print ("This also produces two blank lines\n\n")
print ("\tHi \tHello")
print ("Hello" * 10)
print ("5\t 6\t 7")